#!/bin/sh
cd /var/www/html
scp index.css index.html root@server:/var/www/html/
scp ~/Code/ArcadeMachine/out/artifacts/Client_jar/Client.jar files/startClient.bat root@server:/var/www/html/files
ssh root@server systemctl restart apache2
